### ISSUE TITLE
getLyrics for some bands yields IllegalStateException

### ISSUE THREAD

**Issue by Aarkon** [Loki-Afro/metalarchives#17]
Sorry, it's me again ^^

When I try to query the lyrics e.g. of Metallica, I see the following in my stack trace:

```
Exception in thread "main" java.lang.IllegalStateException: could not find split band from previously parsed disc with id 379007
	at com.github.loki.afro.metallum.entity.Track.createSplitTrack(Track.java:58)
	at com.github.loki.afro.metallum.core.parser.site.helper.disc.DiscSiteTrackParser.parse(DiscSiteTrackParser.java:61)
	at com.github.loki.afro.metallum.core.parser.site.DiscSiteParser.parseTracks(DiscSiteParser.java:70)
	at com.github.loki.afro.metallum.core.parser.site.DiscSiteParser.parse(DiscSiteParser.java:42)
	at com.github.loki.afro.metallum.search.service.advanced.DiscSearchService.lambda$getById$0(DiscSearchService.java:24)
	at com.github.loki.afro.metallum.search.AbstractSearchService.getById(AbstractSearchService.java:49)
	at com.github.loki.afro.metallum.search.API.getDiscById(API.java:50)
	at com.github.loki.afro.metallum.entity.partials.PartialDisc.load(PartialDisc.java:13)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.loki.afro.metallum.entity.Band.getDiscs(Band.java:50)
```

It seems to me that the band did a split at least once which breaks the logic of the `getLyrics` method in some place.

**Comment by Loki-Afro** [comment]
@Aarkon nothing to feel sorry about, you exactly hit those issues that i always had in mind but where i know workarounds but did not find a clean solution :P 

can you provide a hakcy test or some sample code?

**Comment by Aarkon** [comment]
I suppose just trying to fetch lyrics for Metallica should suffice. If I find the time, I can write a simple unit test for that, but you'll probably be faster on your own. 😉

**Comment by Loki-Afro** [comment]
hey @Aarkon could you try out this branch for your usecase `gh-17-splitbands-lyrics` ?

somehow i think i broke more than i fixed, but i'm not sure, the test in that branch is just some hacky code yet

**Comment by Aarkon** [comment]
It's a bit of a hassle for me to locally work with branches of the library, because I use it neither from Java nor from Maven, but I'll give it a shot as soon as I'll find the time.

Yeah, I too saw that HTML coming in and I thought to myself that there should be a clean & simple way to remove it on my side, but you're right, it would be better to fix that as well at the source. ;) This touches the very foundations of your work I suppose, so no bad feelings to address this in a separate issue!

**Comment by Aarkon** [comment]
I'm sorry, but I just can't find the time. Do you need any bit of information that I can provide to conduct tests on your own?

**Comment by Aarkon** [comment]
No trouble mate, I'm grateful for your work anyway!

**Comment by Aarkon** [comment]
Will we see a new release for the commit closing this issue? :)

**Comment by Loki-Afro** [comment]
just release 1.2.0, thanks for reminding, might take a few ours to be on maven central
